"""add_test_assets_table

Revision ID: 0cc711b1534f
Revises: e349fd4ecb14
Create Date: 2026-07-14 12:34:12.435308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc711b1534f'
down_revision: Union[str, Sequence[str], None] = 'e349fd4ecb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='资产名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='资产类型: file/script/data/config/image/other'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='逗号分隔标签'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('content', sa.Text(), nullable=True, comment='文本内容'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_assets')
    # ### end Alembic commands ###
