"""add_knowledge_docs_table

Revision ID: 12a2945e0282
Revises: 0cc711b1534f
Create Date: 2026-07-14 12:38:34.599962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a2945e0282'
down_revision: Union[str, Sequence[str], None] = '0cc711b1534f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_docs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='知识标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='知识正文（Markdown）'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源: file/manual/api'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='逗号分隔标签'),
    sa.Column('collection_name', sa.String(length=50), nullable=False, comment='所属 Qdrant 集合'),
    sa.Column('vector_id', sa.String(length=100), nullable=True, comment='Qdrant 点 ID'),
    sa.Column('vector_synced', sa.Integer(), nullable=False, comment='是否已同步到向量库'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_docs')
    # ### end Alembic commands ###
