"""add_requirements_table

Revision ID: 7d34cab7ed8e
Revises: fd48dc11cd40
Create Date: 2026-07-14 12:26:51.723638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d34cab7ed8e'
down_revision: Union[str, Sequence[str], None] = 'fd48dc11cd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='需求标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='需求描述'),
    sa.Column('module', sa.String(length=100), nullable=True, comment='所属模块'),
    sa.Column('priority', sa.String(length=4), nullable=False, comment='优先级: P0/P1/P2/P3'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft/review/approved/implemented/rejected'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    # ### end Alembic commands ###
