"""add_test_environments_table

Revision ID: e349fd4ecb14
Revises: 7d34cab7ed8e
Create Date: 2026-07-14 12:31:57.288211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e349fd4ecb14'
down_revision: Union[str, Sequence[str], None] = '7d34cab7ed8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_environments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='环境名称'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='环境类型: dev/test/staging/production/custom'),
    sa.Column('config', mysql.JSON(), nullable=True, comment='配置信息'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: preparing/ready/in_use/maintenance/unavailable'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='负责人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_environments')
    # ### end Alembic commands ###
